name: Dependency - Renovate

on:
  pull_request:
    paths:
    - '.github/renovate.json5'
  workflow_dispatch: { }

permissions:
  contents: read

jobs:
  check:
    name: Check renovate config 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - name: Validate renovate config
      uses: docker://renovate/renovate:latest@sha256:48583bdd201a23d0358e08e43b06beabd72e82f55a20604ad1a22b5f75a54573
      with:
        args: renovate-config-validator
