name: Dependency - Renovate

on:
  pull_request:
    paths:
    - '.github/renovate.json5'
  workflow_dispatch: { }

permissions:
  contents: read

jobs:
  check:
    name: Check renovate config 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - name: Validate renovate config
      uses: docker://renovate/renovate:latest@sha256:f468e94c9068b0564b29fef2c1b686329d657da5173d3e24ba624be06254bc24
      with:
        args: renovate-config-validator
