name: Dependency - Renovate

on:
  pull_request:
    paths:
    - '.github/renovate.json5'
  workflow_dispatch: { }

permissions:
  contents: read

jobs:
  check:
    name: Check renovate config 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
    - name: Validate renovate config
      uses: docker://renovate/renovate:latest@sha256:65f48c2598eca12b7f448130a12f43a54fa9d6017e7fcf54c7e3c526bd9de626
      with:
        args: renovate-config-validator
